### ISSUE TITLE
Latest update crashes any saved game back to the title screen

### ISSUE THREAD

**Issue by MrDioneo** [microsoftenator2022/WrathPatches#1]
I have been using your mod (along with a bunch of others) for quite a while without issue.  I had taken a week or so off from playing, and when I tried to load my last save, it would get stuck halfway and then return to the title screen.  The same with any past saves.  After going back through the latest mods to have received updates (I use Modfinder to manage them) since I last played I eventually ended up fixing it by disabling this one.  Obviously with a bunch of other mods in play this is complicated.  Are there any log files that I could provide to you that would help.  If you care to look into this?

**Comment by aaronmaslen** [comment]
I will need GameLogFull.txt and Player.log

With WrathPatches 1.10+ you can get these by pressing Ctrl+Alt+Shift+F

**Comment by MrDioneo** [comment]
Your new update fixed whatever the problem may have been.  I can load my
saves with it enabled again!
