### ISSUE TITLE
Game stuck on loading on launch

### ISSUE THREAD

**Issue by ntoxeg** [microsoftenator2022/WrathPatches#3]
Version: 1.12.0

Game doesn’t load into the main menu, it just hangs forever.
Downgrading to 1.11.0 restores proper function.

It seems there are lots of `C:\Users\Aaron\source\repos\Wotr\WrathPatches\WrathPatches\Patches\TheEnhance.cs:164` mentions in the logs.
[GameLogFull.txt](https://github.com/user-attachments/files/16802201/GameLogFull.txt)
[Player.log](https://github.com/user-attachments/files/16802203/Player.log)

**Comment by Xyrmes** [comment]
I had this issue, too.

**Comment by microsoftenator2022** [comment]
Do you have OwlcatModificationManagerSettings.json in the folder with the logs?

**Comment by microsoftenator2022** [comment]
1.12.1 should fix this

**Comment by ntoxeg** [comment]
> Do you have OwlcatModificationManagerSettings.json in the folder with the logs?

I don’t have that file.
That said, 1.12.1 does not have this issue indeed.

**Comment by ntoxeg** [comment]
I guess that fixes it.
